### ISSUE TITLE
I keep getting Class not found yaml.Yaml etc

### ISSUE THREAD

**Issue by jblom** [mikestead/hx-yaml#10]
Hello Mike,

I'd love to use this in my haxe project, but I always seem to get class not found errors... 

I have tried installing it with:

haxelib yaml
haxelib local hx-yaml-master.zip
haxelib dec yaml /mydir/hx-yaml-master/src
haxelib git yaml https://github.com/mikestead/hx-yaml.git src

but when I simply import:

import yaml.Yaml;
import yaml.Parser; 
etc

I always get a class not found yaml:Yaml etc

What am I doing wrong? 

Kind regards,

Jaap

**Comment by mikestead** [comment]
I assume you mean `haxelib install yaml`?

Did you add it to your `.hxml` file as a lib?

    -lib yaml

**Comment by jblom** [comment]
Yes I meant haxelib install yaml. 

And thanks! Did not know that I needed to add it there as well. Was working with someone else on the same code project and I guess he was the one to usually add new external libs to that file. (He occasionally said something like: "after you pull the code run haxelib install xyz" and then it worked of course, but I did not notice him extending that file ;-) )

Anyway: thanks! (sorry for the noob question)

**Comment by mikestead** [comment]
no problem

**Comment by Misiur** [comment]
Sorry for gravedigging, but for people like me who want to run git version, you need to run
`haxelib dev yaml /path/to/haxe/lib/yaml/git/src`, otherwise you'll get errors like "Type not found: yaml.Yaml" because it will be pointing at `git` folder, which doesn't have the `haxelib.json`
