### ISSUE TITLE
!Tag support

### ISSUE THREAD

**Issue by fzzr-** [mikestead/hx-yaml#9]
How to implement `!customTag` support? ([spec](http://www.yaml.org/spec/1.2/spec.html#!%20tag%20indicator//))

**Comment by mikestead** [comment]
@fzzr- Sorry I don't believe there's support for this currently. I can see over over on js-yaml they have support so shouldn't be too hard to port over. https://github.com/nodeca/js-yaml/blob/master/examples/custom_types.js

Don't have time myself right now but always open to pull requests.

**Comment by mikestead** [comment]
closing as stale
